### ISSUE TITLE
help please with a concat issue

### ISSUE THREAD

**Issue by mdsumner** [zarr-developers/VirtualiZarr#289]
I have a virtualization scheme for a "daily" time series of a projected netcdf, with a problem at concatenation that I have isolated one element at steps 1716:1718.  Other ranges in the sequence concatenate without problem, but there are other problem elements later in the sequence that I haven't pinned yet.  

(I say "daily" because it is mixed, starting at every two days, moving to every day, and then with a ~21ish day gap in the sequence - these are filled with dummy files that do not have the primary variable `NO7_ICECON`, and I've flushed those out from the set already). 

here's the error message for the whole set

```python
vds = xarray.concat(vd0, dim = 'time', coords = 'minimal', compat = 'override')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/concat.py", line 277, in concat
    return _dataset_concat(
           ^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/concat.py", line 674, in _dataset_concat
    combined_var = reindex_variables(
                   ^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/alignment.py", line 79, in reindex_variables
    new_var = var._getitem_with_mask(indxr, fill_value=fill_value_)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/variable.py", line 851, in _getitem_with_mask
    data = indexing.apply_indexer(indexable, actual_indexer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 1031, in apply_indexer
    return indexable.oindex[indexer]
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 369, in __getitem__
    return self.getter(key)
           ^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 1508, in _oindex_get
    return self.array[key]
           ~~~~~~~~~~^^^^^
  File "/home/mdsumner/.local/lib/python3.12/site-packages/virtualizarr/manifests/array.py", line 233, in __getitem__
    raise NotImplementedError(f"Doesn't support slicing with {indexer}")
NotImplementedError: Doesn't support slicing with (array([ 0,  1,  2, ..., -1, -1, -1]), slice(None, None, None), slice(None, None, None))
```

those were opened with

```
open_virtual_dataset(filepath, indexes = {}, 
                              loadable_variables=['x', 'y', 'time', 'crs'], 
                              decode_times = True, reader_options={'storage_options': creds})
```

the first problem instance is `1717` as we see here: 

```python
 vd0[1716:1718],
([<xarray.Dataset> Size: 110kB
Dimensions:     (time: 1, y: 332, x: 316)
Coordinates:
  * x           (x) float64 3kB -3.938e+06 -3.912e+06 ... 3.912e+06 3.938e+06
  * y           (y) float64 3kB 4.338e+06 4.312e+06 ... -3.912e+06 -3.938e+06
  * time        (time) datetime64[ns] 8B 1987-08-20
Data variables:
    N07_ICECON  (time, y, x) uint8 105kB ManifestArray<shape=(1, 332, 316), d...
    crs         |S1 1B ...
Attributes: (12/49)
    Conventions:               CF-1.6, ACDD-1.3
    acknowledgment:            These data are produced by the NASA Cryospheri...
    cdm_data_type:             grid
    citation:                  DiGirolamo, N. E., C. L. Parkinson, D. J. Cava...
    contributor_name:          Nicolo E. DiGirolamo, Claire Parkinson, Per Gl...
    contributor_role:          project_scientist, project_scientist, project_...
    ...                        ...
    summary:                   This data set is generated from brightness tem...
    time_coverage_duration:    1987-08-20T00:00P1D
    time_coverage_end:         1987-08-20 23:59.99
    time_coverage_resolution:  P1D
    time_coverage_start:       1987-08-20 00:00.00
    title:                     Sea Ice Concentrations from Nimbus-7 SMMR and ..., 


<xarray.Dataset> Size: 110kB
Dimensions:     (time: 1, y: 332, x: 316)
Coordinates:
  * x           (x) float64 3kB -3.938e+06 -3.912e+06 ... 3.912e+06 3.938e+06
  * y           (y) float64 3kB 4.338e+06 4.312e+06 ... -3.912e+06 -3.938e+06
  * time        (time) datetime64[ns] 8B 1987-08-21
Data variables:
    F08_ICECON  (time, y, x) uint8 105kB ManifestArray<shape=(1, 332, 316), d...
    crs         |S1 1B ...
Attributes: (12/49)
    Conventions:               CF-1.6, ACDD-1.3
    acknowledgment:            These data are produced by the NASA Cryospheri...
    cdm_data_type:             grid
    citation:                  DiGirolamo, N. E., C. L. Parkinson, D. J. Cava...
    contributor_name:          Nicolo E. DiGirolamo, Claire Parkinson, Per Gl...
    contributor_role:          project_scientist, project_scientist, project_...
    ...                        ...
    summary:                   This data set is generated from brightness tem...
    time_coverage_duration:    1987-08-21T00:00P1D
    time_coverage_end:         1987-08-21 23:59.99
    time_coverage_resolution:  P1D
    time_coverage_start:       1987-08-21 00:00.00
    title:                     Sea Ice Concentrations from Nimbus-7 SMMR and ...],)
```

when we concatenate it fails

```python
xarray.concat(vd0[1716:1718], dim = 'time', coords = 'minimal', compat = 'override')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/concat.py", line 277, in concat
    return _dataset_concat(
           ^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/concat.py", line 674, in _dataset_concat
    combined_var = reindex_variables(
                   ^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/alignment.py", line 79, in reindex_variables
    new_var = var._getitem_with_mask(indxr, fill_value=fill_value_)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/variable.py", line 851, in _getitem_with_mask
    data = indexing.apply_indexer(indexable, actual_indexer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 1031, in apply_indexer
    return indexable.oindex[indexer]
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 369, in __getitem__
    return self.getter(key)
           ^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/xarray/core/indexing.py", line 1508, in _oindex_get
    return self.array[key]
           ~~~~~~~~~~^^^^^
  File "/home/mdsumner/.local/lib/python3.12/site-packages/virtualizarr/manifests/array.py", line 233, in __getitem__
    raise NotImplementedError(f"Doesn't support slicing with {indexer}")
NotImplementedError: Doesn't support slicing with (array([ 0, -1]), slice(None, None, None), slice(None, None, None))

```

and other sequences like `[0:1500]` or `[1718:1720]` work fine. 

The full workflow is here if that's needed, it should be reproducible and easy to run apart from obtaining `n` for the available cpus (which I'm sure there's a better style generally - with 24 cpus it runs within ~4min - ((Hobart TAS<->Perth WA))). 

```python
from virtualizarr import open_virtual_dataset
import pyarrow.parquet
import fsspec
import os
import dask.multiprocessing
import xarray

parquetfile = "https://projects.pawsey.org.au/idea-objects/idea-objects.parquet"


n = int(os.environ["SLURM_JOB_CPUS_PER_NODE"])

dask.config.set(scheduler='processes', num_workers = n)  

bucket = 'idea-10.5067-mpyg15waa4wx'
## dataset = 'nsidc25ksouth'
aws_credentials = {"endpoint_url": "https://projects.pawsey.org.au",  "anon": True}

with fsspec.open(parquetfile) as f:
    s3table = pyarrow.parquet.read_table(f, filters=[('Bucket','==', bucket)])


nclist = s3table.to_pandas().Key.tolist()
nc = [f's3://{bucket}/{nc0}' for nc0 in nclist]
nc.sort()


## return None if the file is a dummy containter
def open_virtual(filepath, creds):
  ds = open_virtual_dataset(filepath, indexes = {}, 
                              loadable_variables=['x', 'y', 'time', 'crs'], 
                              decode_times = True, reader_options={'storage_options': creds})
  if len(ds.keys()) > 1: 
    return(ds) 
  else: 
    return(None)



vdd = [
  dask.delayed(open_virtual)(filepath, aws_credentials)
  for filepath in nc]


vd = dask.compute(vdd)

## flush out the dummy slices (we gave None from the virtualization step)
vd0 = [x for x in vd[0] if x is not None]

## BAP unfortunately
vds = xarray.concat(vd0, dim = 'time', coords = 'minimal', compat = 'override')

```

Thanks!!  Appreciate any pointers this represents quite a lot of slow progress for me, other datasets have been unproblematic.

**Comment by keewis** [comment]
I think this is because you have some corrupted files in that dataset: they are missing the `N07_ICECON` variable – or at least, that's what I got while trying to reproduce, your output shows that you appear to have a slightly different issue where one of the variables is called `F08_ICECON` while the other is `N07_ICECON`.

To get that to work you might have to split the urls by the variable in the dataset, concat datasets with common variables, then merge the concatenated datasets together using `xr.merge` (this is what `xr.combine_*` is supposed to do, but I don't know if that works already).

Obviously, if the files are truly corrupted all you can do is trying to fix or skip them.

**Comment by mdsumner** [comment]
Oh! Sorry, entirely about the different name ... I had been aware of that in the past. Thanks for the advice on how to deal with it!

**Comment by mdsumner** [comment]
I might just

**Comment by mdsumner** [comment]
fun stuff, so these files can have 0, 1, 2, or 3 variables of that form "{code}_ICECON", and I only want one. I'll have to rejig how this gets done and prefilter for a preferred var (when one exists), I think.   I wonder if I should establish all of them as vzarrs, and then look at normalizing, so maybe I should just be combine(ing). 

I might ask more widely on discourse, it's really multiple datasets with the capacity to pick one consistent time series across overlapping eras. I'm stuck on what's a good way forward, I don't want to publish a changed dataset, just give access to low-expertise users to "ok data" over the longest possible time range. (but maybe I should rewrite entirely to a Zarr given that I'm not interested in fidelity to the complexities of the current netcdfs).
